#using output resource block for output variables
resource "random_pet" "my-pet" {

  length    = var.length 
}

output "pet-name" {
	
	value = random_pet.my-pet.id  # using output resouce to show the id attribute value of random_pet resource
	description = "Record the value of pet ID generated by the random_pet resource"
}

resource "local_file" "welcome" {
    filename = "/home/prithvi/terraform-practice/practice_5/message.txt"
    content = "Welcome to Kodekloud."
}

output "welcome_message" {
  value = local_file.welcome.content  # using output resouce to show the content attribute value of welcome resource
}

# to see the value of output variables use "terraform output"